# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productot',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
