# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productot',
            options={'ordering': ('id',)},
        ),
    ]
