# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productot',
            name='message',
            field=models.CharField(default=datetime.datetime(2016, 2, 29, 0, 0, 32, 29000, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
