# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productot_message2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productot',
            name='message2',
        ),
        migrations.AlterField(
            model_name='productot',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
