# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_productot_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productot',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
